@startuml

title __UTILITY's Class Diagram__\n

  namespace utility {
    class utility.AppointmentDB {
        {static} + addAppointment()
        {static} + appointmentsByContactId()
        {static} + appointmentsByTypeAndMonth()
        {static} + deleteAppointment()
        {static} + deleteAssociatedAppointments()
        {static} + getAllAppointments()
        {static} + getAllMonthlyAppointments()
        {static} + getAllWeeklyAppointments()
        {static} + getAppointmentsIn15Minutes()
        {static} + overlappingAppointments()
        {static} + studentsNeedFollowUp()
        {static} + updateAppointment()
    }
  }
  

  namespace utility {
    class utility.ContactDB {
        {static} + getAllContactNames()
        {static} + getContactId()
    }
  }
  

  namespace utility {
    class utility.CountryDB {
        {static} + getAllCountries()
    }
  }
  

  namespace utility {
    class utility.CustomerDB {
        {static} + addInstructor()
        {static} + addStudent()
        {static} + deleteCustomer()
        {static} + getAllCustomers()
        {static} + getAllInstructors()
        {static} + getAllStudents()
        {static} + getInstructorId()
        {static} + getInstructorProgram()
        {static} + getStudentId()
        {static} + getStudentProgram()
        {static} + updateInstructor()
        {static} + updateStudent()
    }
  }
  

  namespace utility {
    class utility.DivisionDB {
        {static} + getAllCanadaDivisions()
        {static} + getAllUKDivisions()
        {static} + getAllUSDivisions()
        {static} + getDivisionId()
    }
  }
  

  namespace utility {
    abstract class utility.JDBC {
        {static} - connection : Connection
        {static} - databaseName : String
        {static} - driver : String
        {static} - jdbcUrl : String
        {static} - location : String
        {static} - password : String
        {static} - preparedStatement : PreparedStatement
        {static} - protocol : String
        {static} - userName : String
        {static} - vendor : String
        {static} + closeConnection()
        {static} + getConnection()
        {static} + getPreparedStatement()
        {static} + makeConnection()
        {static} + makePreparedStatement()
    }
  }
  

  namespace utility {
    class utility.UserDB {
        {static} + currentUser : User
        {static} + userCurrentTime : LocalDateTime
        {static} + userTimeZone : ZoneId
        {static} + getAllUsers()
        {static} + getCurrentUser()
        {static} + getUserCurrentTime()
        {static} + getUserTimeZone()
        {static} + validateLogin()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
